package clashsoft.mods.tml;

import java.io.File;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.List;

import clashsoft.cslib.minecraft.update.CSUpdate;
import clashsoft.mods.tml.jmod.TextMod;
import clashsoft.mods.tml.jmod.methods.block.MethodAddBlock;
import clashsoft.mods.tml.jmod.methods.block.MethodAddSpecialBlock;
import clashsoft.mods.tml.jmod.methods.crafting.MethodAddFuel;
import clashsoft.mods.tml.jmod.methods.crafting.MethodCrafting;
import clashsoft.mods.tml.jmod.methods.crafting.MethodCraftingShapeless;
import clashsoft.mods.tml.jmod.methods.crafting.MethodSmelting;
import clashsoft.mods.tml.jmod.methods.item.MethodAddItem;
import clashsoft.mods.tml.jmod.methods.util.MethodHelp;
import clashsoft.mods.tml.jmod.methods.util.MethodToString;
import clashsoft.mods.tml.jmod.util.TextModHelper;
import cpw.mods.fml.common.*;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.relauncher.Side;

import net.minecraft.client.Minecraft;
import net.minecraft.server.MinecraftServer;
import net.minecraftforge.common.MinecraftForge;

@Mod(modid = TextModLoader.MODID, name = TextModLoader.NAME, version = TextModLoader.VERSION)
public class TextModLoader implements TextModConstants
{
	public static final String		MODID			= "textmodloader";
	public static final String		NAME			= "Text Mod Loader";
	public static final String		VERSION			= CSUpdate.CURRENT_VERSION + "-0.0.0";
	
	@Instance(MODID)
	public static TextModConstants	instance;
	
	public static List<TextMod>		loadedTextMods	= new LinkedList<TextMod>();
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event)
	{
		ModMetadata meta = event.getModMetadata();
		meta.autogenerated = false;
		meta.credits = "(c) Clashsoft, 2013";
		meta.authorList = Arrays.asList("Clashsoft");
		
		meta.modId = "TextModLoader";
		meta.name = "TextMod Loader";
		meta.version = VERSION;
		
		meta.description = "TextMod Loader is a small mod that loads, parses and executes .textmod files in your mods directory.";
	}
	
	@EventHandler
	public void init(FMLInitializationEvent event)
	{
		System.out.println("Loading TextModLoader");
		System.out.println("Registering Method Executers");
		
		GameRegistry.registerFuelHandler(new MethodAddFuel());
		
		TextModHelper.registerMethodExecuter(new MethodAddBlock());
		TextModHelper.registerMethodExecuter(new MethodAddSpecialBlock());
		TextModHelper.registerMethodExecuter(new MethodAddItem());
		
		TextModHelper.registerMethodExecuter(new MethodCrafting());
		TextModHelper.registerMethodExecuter(new MethodCraftingShapeless());
		TextModHelper.registerMethodExecuter(new MethodSmelting());
		TextModHelper.registerMethodExecuter(new MethodAddFuel());
		
		TextModHelper.registerMethodExecuter(new MethodHelp());
		TextModHelper.registerMethodExecuter(new MethodToString());
		
		System.out.println(TextModHelper.methods.size() + " Method Executors registered.");
		
		try
		{
			File file;
			if (FMLCommonHandler.instance().getEffectiveSide() == Side.CLIENT)
				file = new File(Minecraft.getMinecraft().mcDataDir.getPath(), "mods");
			else
				file = new File(MinecraftServer.getServer().getFolderName(), "mods");
			List<File> files = getTextModDirectories(file);
			
			for (File f : files)
			{
				loadModClass(f);
				for (File g : f.listFiles())
				{
					loadModClass(g);
				}
			}
			
			float averageLoadTime = 0L;
			if (loadedTextMods.size() > 0)
			{
				for (TextMod tm : loadedTextMods)
					averageLoadTime += tm.getTotalLoadingTime();
				averageLoadTime /= loadedTextMods.size();
			}
			System.out.println(files.size() + " TextMod" + (files.size() == 1 ? "" : "s") + " loaded. Average loading time: " + averageLoadTime);
		}
		catch (NoClassDefFoundError error)
		{
			error.printStackTrace();
		}
		
		MinecraftForge.EVENT_BUS.register(this);
	}
	
	private List<File> getTextModDirectories(File path)
	{
		List<File> files = new LinkedList<File>();
		for (File f : path.listFiles())
		{
			if (f != null && f.isDirectory())
				files.add(f);
		}
		return files;
	}
	
	private void loadModClass(final File modClass)
	{
		if (modClass.getName().endsWith(JAVA_MOD_SUFFIX))
		{
			if (ENABLE_THREADING)
				new Thread(new Runnable()
				{
					@Override
					public void run()
					{
						TextMod.load(modClass);
					}
				}).start();
			else {
				TextMod.load(modClass);}
		}
	}
}